In [1]:
#Chaning class attributes
class MyClass:
    count = 0
MyClass.count = 10

In [3]:
class MyClass:
    def __init__(self):
        self.value = 0
obj = MyClass()
obj.value = 10

In [7]:
class MyClass:
    def my_method(self):
        print("Hello,Everyone!")
class MySubclass(MyClass):
    def my_method(self):
        print("ThankYou")
obj = MySubclass()
obj.my_method()

ThankYou


In [8]:
class MyClass:
    def my_method(self):
        print("Hello,Everyone!")
obj = MyClass()
obj.my_method = lambda:print("ThankYou")
obj.my_method()

ThankYou


In [10]:
#Polymorphism
class sample:
    def __len__(self):
        return 30
if __name__ == "__main__":
    str = sample()
    print(len(str))

30


In [12]:
class Vector:
    def __init__(self,x,y):
        self.x = x
        self.y = y
    def __add__(self,other):
        return Vector(self.x + other.x,self.y + other.y)
v1 = Vector(1,2)
v2 = Vector(3,4)
v3 = v1 + v2
print(v3.x,v3.y)

4 6


In [13]:
#Encapsulation
class Person:
    def __init__(self,name,age):
        self.name = name
        self.__age = age
    
    def get_age(self):
        return self.__age
    
    def set_age(self,age):
        if age > 0 and age < 120:
            self.__age = age
    
    def display(self):
        print(f"Name: {self.name}, Age: {self.__age}")

person = Person("John",30)
person.display()
person.set_age(35)
person.display()
print(person.get_age())

Name: John, Age: 30
Name: John, Age: 35
35


In [19]:
#Abstraction
from abc import ABC,abstractmethod

class Subject(ABC):
    @abstractmethod
    def subject(self):
        pass

class History(Subject):
    def subject(self):
        print("Subject is History")

class Civics(Subject):
    def subject(self):
        print("Subject is Civics")
        
class Geography(Subject):
    def subject(self):
        print("Subject is Geography")
        
class Economics(Subject):
    def subject(self):
        print("Subject is Economics")
        
history = History()
history.subject()
civics = Civics()
civics.subject()
geography = Geography()
geography.subject()
economics = Economics()
economics.subject()

Subject is History
Subject is Civics
Subject is Geography
Subject is Economics


In [ ]:
#Method overriding

In [ ]:
#method overloading

In [20]:
#Numpy 
import numpy as np

In [22]:
#defining a list of different car companies or string element
arr_str = ["Mercedes","Bmw","Audi","Ferrari","Tesla"]
#defining a list of number of cyliners in car or numerical elements
arr_num = [5,4,6,7,3]

In [24]:
#converting list to numpy array
np_arr_str = np.array(arr_str)
np_arr_num = np.array(arr_num)

#checking the output
print("Numpy Array (arr_str):",np_arr_str)
print("Numpy Array (arr_num):",np_arr_num)

Numpy Array (arr_str): ['Mercedes' 'Bmw' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num): [5 4 6 7 3]


In [26]:
#printing the data type of lists
print("data type of arr_str: ",type(arr_str))
print("data type of arr_num: ",type(arr_num))

#printing the data type after converion of lists to array
print("data type of np_arr_str: ",type(np_arr_str))
print("data type of np_arr_num: ",type(np_arr_num))


data type of arr_str:  <class 'list'>
data type of arr_num:  <class 'list'>
data type of np_arr_str:  <class 'numpy.ndarray'>
data type of np_arr_num:  <class 'numpy.ndarray'>


In [30]:
#Numpy matrix
matrix = np.array([[1,2,2],[3,4,5],[5,6,7]])
print(matrix)
print("Data type of matrix: ",type(matrix))

[[1 2 2]
 [3 4 5]
 [5 6 7]]
Data type of matrix:  <class 'numpy.ndarray'>


In [ ]:
#Numpy functions