In [5]:
#Numpy functions
import numpy as np

In [6]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr2 = np.arange(start=0,stop=10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr2=np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr3 = np.arange(start=0,stop=20,step=5)
arr3

array([ 0,  5, 10, 15])

In [11]:
#linspace
matrix2 = np.linspace(
    0,5
)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [12]:
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [13]:
#np.zeros()
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
#np,ones()
matrix5 = np.ones([3,5])
matrix5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#np.eyes
matrix6 = np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#reshape
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr4_reshaped = arr4.reshape((2,5))
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
arr4_reshaped = arr4.reshape([2,5])
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
#trignometric functions
print("Sine function:",np.sin(4))
print("Cos function:",np.cos(4))

Sine function: -0.7568024953079282
Cos function: -0.6536436208636119


In [22]:
#Exponenet & logarthimic functions
np.exp(2)

7.38905609893065

In [24]:
arr5 = np.array([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [25]:
np.log(2)

0.6931471805599453

In [26]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [27]:
np.log10(2)

0.3010299956639812

In [28]:
#Arithmatric operations
l1 = [1,2,3]
l2 = [4,5,6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [29]:
arr7 = np.arange(1,6)
print("arr7:",arr7)

arr8 = np.arange(3,8)
print("arr8:",arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [30]:
print("Add:", arr7+arr8)
print("sub:", arr7-arr8)
print("multi:", arr7 * arr8)
print("divide:", arr7 / arr8)
print("inverse:", 1 / arr7)
print("powrs:", arr7 ** arr8)

Add: [ 4  6  8 10 12]
sub: [-2 -2 -2 -2 -2]
multi: [ 3  8 15 24 35]
divide: [0.33333333 0.5        0.6        0.66666667 0.71428571]
inverse: [1.         0.5        0.33333333 0.25       0.2       ]
powrs: [    1    16   243  4096 78125]


In [31]:
#operations on matrices

In [32]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)
matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
print("Add: ", matrix7 + matrix8)
print("Sub: ", matrix7 - matrix8)
print("Multi: ", matrix7 * matrix8)
print("Division: ", matrix7 / matrix8)

Add:  [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Sub:  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multi:  [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division:  [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\jayesh.verma\AppData\Local\Temp\ipykernel_21976\3575549128.py:4: RuntimeWarning: divide by zero encountered in divide
  print("Division: ", matrix7 / matrix8)


In [35]:
#linear algebra matrix multiplication
matrix9 = np.arange(1,10).reshape(3,3)
print("First Matrix : \n",matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print("Second Matrix : \n",matrix10)
#dot product
print("Multiplication :",matrix9 @ matrix10)

First Matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix : 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplication : [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [36]:
#Transpose of a matrix
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])